import type { Character } from './model'

/**
 * 建安十三年（208 年）的人物数据，按所在州分布，供寻访抽取。
 * 在仕者驻守各自势力的战略点并统率一支部队；不在三家之列的势力，其部属按在野处理。
 * 在野者标注寻访卡池层级：荆襄名士置于基础池，保证刘备据江夏时可在荆州寻得；名将置于高层。
 * 势力倾向记各将对各势力的偏好（0–100，50 为中性），只记非中性者；忠诚与性格另按人给定，与偏好无关。
 * 能力与兵力取自演义印象，年龄按史书推算，具体平衡待核心玩法验证后再调。
 */
export const CHARACTERS_SANGUO: Character[] = [
  // 刘备（荆州）
  { id: 'liubei', name: '刘备', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 73, command: 75, intellect: 76, politics: 80, age: 47, personality: 'open', affinities: { liubei: 98 }, loyalty: 100, isMonarch: true, stationedSiteId: 'jiangxia', troops: 5000, tier: null },
  { id: 'guanyu', name: '关羽', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 97, command: 95, intellect: 75, politics: 45, age: 48, personality: 'proud', affinities: { liubei: 96, caocao: 70, sunquan: 30 }, loyalty: 98, isMonarch: false, stationedSiteId: 'jiangxia', troops: 8000, tier: null },
  { id: 'zhangfei', name: '张飞', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 98, command: 85, intellect: 40, politics: 30, age: 42, personality: 'brave', affinities: { liubei: 95 }, loyalty: 96, isMonarch: false, stationedSiteId: 'jiangxia', troops: 6000, tier: null },
  { id: 'zhaoyun', name: '赵云', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 96, command: 91, intellect: 76, politics: 50, age: 40, personality: 'steady', affinities: { liubei: 90 }, loyalty: 97, isMonarch: false, stationedSiteId: 'jiangxia', troops: 4000, tier: null },
  { id: 'zhugeliang', name: '诸葛亮', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 38, command: 92, intellect: 100, politics: 95, age: 27, personality: 'cautious', affinities: { liubei: 92 }, loyalty: 100, isMonarch: false, stationedSiteId: 'jiangxia', troops: 2000, tier: null },
  { id: 'mizhu', name: '糜竺', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 30, command: 45, intellect: 72, politics: 78, age: 43, personality: 'steady', affinities: { liubei: 85 }, loyalty: 90, isMonarch: false, stationedSiteId: 'jiangxia', troops: 1000, tier: null },
  { id: 'jianyong', name: '简雍', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 25, command: 40, intellect: 70, politics: 72, age: 48, personality: 'open', affinities: { liubei: 82 }, loyalty: 88, isMonarch: false, stationedSiteId: 'jiangxia', troops: 800, tier: null },
  { id: 'sunqian', name: '孙乾', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 28, command: 42, intellect: 71, politics: 74, age: 43, personality: 'steady', affinities: { liubei: 80 }, loyalty: 87, isMonarch: false, stationedSiteId: 'jiangxia', troops: 800, tier: null },
  { id: 'chendao', name: '陈到', status: 'serving', factionId: 'liubei', provinceId: 'jing', might: 85, command: 80, intellect: 60, politics: 45, age: 28, personality: 'brave', affinities: { liubei: 88 }, loyalty: 92, isMonarch: false, stationedSiteId: 'jiangxia', troops: 2000, tier: null },

  // 曹操（豫州）
  { id: 'caocao', name: '曹操', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 72, command: 96, intellect: 91, politics: 92, age: 53, personality: 'scheming', affinities: { caocao: 98 }, loyalty: 100, isMonarch: true, stationedSiteId: 'xudu', troops: 20000, tier: null },
  // 曹操（司隶）
  { id: 'xiahoudun', name: '夏侯惇', status: 'serving', factionId: 'caocao', provinceId: 'sili', might: 90, command: 88, intellect: 55, politics: 60, age: 51, personality: 'brave', affinities: { caocao: 95 }, loyalty: 95, isMonarch: false, stationedSiteId: 'luoyang', troops: 8000, tier: null },
  { id: 'xiahouyuan', name: '夏侯渊', status: 'serving', factionId: 'caocao', provinceId: 'sili', might: 91, command: 90, intellect: 60, politics: 55, age: 51, personality: 'brave', affinities: { caocao: 92 }, loyalty: 93, isMonarch: false, stationedSiteId: 'sishui', troops: 8000, tier: null },
  { id: 'jiaxu', name: '贾诩', status: 'serving', factionId: 'caocao', provinceId: 'sili', might: 45, command: 70, intellect: 97, politics: 85, age: 61, personality: 'scheming', affinities: { caocao: 65 }, loyalty: 82, isMonarch: false, stationedSiteId: 'hulao', troops: 2000, tier: null },
  // 曹操（豫州）
  { id: 'xunyu', name: '荀彧', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 30, command: 60, intellect: 96, politics: 96, age: 45, personality: 'steady', affinities: { caocao: 80 }, loyalty: 88, isMonarch: false, stationedSiteId: 'xudu', troops: 1000, tier: null },
  { id: 'xunyou', name: '荀攸', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 32, command: 62, intellect: 94, politics: 90, age: 51, personality: 'cautious', affinities: { caocao: 85 }, loyalty: 87, isMonarch: false, stationedSiteId: 'xudu', troops: 1000, tier: null },
  { id: 'guojia', name: '郭嘉', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 30, command: 65, intellect: 98, politics: 88, age: 38, personality: 'open', affinities: { caocao: 88 }, loyalty: 86, isMonarch: false, stationedSiteId: 'xudu', troops: 1000, tier: null },
  { id: 'caoren', name: '曹仁', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 89, command: 90, intellect: 68, politics: 70, age: 40, personality: 'steady', affinities: { caocao: 94 }, loyalty: 94, isMonarch: false, stationedSiteId: 'xiaopei', troops: 6000, tier: null },
  { id: 'caohong', name: '曹洪', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 86, command: 78, intellect: 50, politics: 55, age: 39, personality: 'brave', affinities: { caocao: 90 }, loyalty: 92, isMonarch: false, stationedSiteId: 'xiaopei', troops: 4000, tier: null },
  { id: 'xuchu', name: '许褚', status: 'serving', factionId: 'caocao', provinceId: 'yu', might: 96, command: 68, intellect: 30, politics: 25, age: 38, personality: 'brave', affinities: { caocao: 93 }, loyalty: 95, isMonarch: false, stationedSiteId: 'xiaopei', troops: 3000, tier: null },
  // 曹操（兖州）
  { id: 'chengyu', name: '程昱', status: 'serving', factionId: 'caocao', provinceId: 'yan', might: 45, command: 74, intellect: 92, politics: 88, age: 67, personality: 'scheming', affinities: { caocao: 86 }, loyalty: 85, isMonarch: false, stationedSiteId: 'chenliu', troops: 2000, tier: null },
  { id: 'yujin', name: '于禁', status: 'serving', factionId: 'caocao', provinceId: 'yan', might: 82, command: 87, intellect: 62, politics: 68, age: 40, personality: 'cautious', affinities: { caocao: 84 }, loyalty: 84, isMonarch: false, stationedSiteId: 'puyang', troops: 5000, tier: null },
  { id: 'yuejin', name: '乐进', status: 'serving', factionId: 'caocao', provinceId: 'yan', might: 88, command: 82, intellect: 55, politics: 50, age: 48, personality: 'brave', affinities: { caocao: 88 }, loyalty: 90, isMonarch: false, stationedSiteId: 'baima', troops: 5000, tier: null },
  { id: 'lidian', name: '李典', status: 'serving', factionId: 'caocao', provinceId: 'yan', might: 78, command: 80, intellect: 72, politics: 70, age: 34, personality: 'steady', affinities: { caocao: 85 }, loyalty: 88, isMonarch: false, stationedSiteId: 'chenliu', troops: 3000, tier: null },
  // 曹操（徐州）
  { id: 'zhangliao', name: '张辽', status: 'serving', factionId: 'caocao', provinceId: 'xu', might: 92, command: 93, intellect: 78, politics: 65, age: 39, personality: 'steady', affinities: { caocao: 88, liubei: 65 }, loyalty: 85, isMonarch: false, stationedSiteId: 'xiapi', troops: 7000, tier: null },
  { id: 'xuhuang', name: '徐晃', status: 'serving', factionId: 'caocao', provinceId: 'xu', might: 91, command: 89, intellect: 70, politics: 60, age: 39, personality: 'steady', affinities: { caocao: 86 }, loyalty: 86, isMonarch: false, stationedSiteId: 'pengcheng', troops: 6000, tier: null },
  // 曹操（冀州）
  { id: 'zhanghe', name: '张郃', status: 'serving', factionId: 'caocao', provinceId: 'ji', might: 88, command: 90, intellect: 76, politics: 68, age: 41, personality: 'cautious', affinities: { caocao: 70 }, loyalty: 80, isMonarch: false, stationedSiteId: 'ye', troops: 6000, tier: null },
  { id: 'gaolan', name: '高览', status: 'serving', factionId: 'caocao', provinceId: 'ji', might: 85, command: 80, intellect: 62, politics: 45, age: 38, personality: 'steady', affinities: { caocao: 68 }, loyalty: 78, isMonarch: false, stationedSiteId: 'nanpi', troops: 4000, tier: null },
  { id: 'caochun', name: '曹纯', status: 'serving', factionId: 'caocao', provinceId: 'ji', might: 85, command: 84, intellect: 66, politics: 60, age: 38, personality: 'brave', affinities: { caocao: 90 }, loyalty: 90, isMonarch: false, stationedSiteId: 'ye', troops: 4000, tier: null },
  // 曹操（荆州）
  { id: 'wenpin', name: '文聘', status: 'serving', factionId: 'caocao', provinceId: 'jing', might: 82, command: 84, intellect: 68, politics: 66, age: 38, personality: 'steady', affinities: { caocao: 72 }, loyalty: 82, isMonarch: false, stationedSiteId: 'jiangling', troops: 4000, tier: null },
  { id: 'caimao', name: '蔡瑁', status: 'serving', factionId: 'caocao', provinceId: 'jing', might: 65, command: 70, intellect: 66, politics: 60, age: 43, personality: 'scheming', affinities: { caocao: 30 }, loyalty: 70, isMonarch: false, stationedSiteId: 'xiangyang', troops: 3000, tier: null },

  // 孙权（扬州）
  { id: 'sunquan', name: '孙权', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 70, command: 82, intellect: 80, politics: 88, age: 26, personality: 'cautious', affinities: { sunquan: 98 }, loyalty: 100, isMonarch: true, stationedSiteId: 'jianye', troops: 15000, tier: null },
  { id: 'zhouyu', name: '周瑜', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 78, command: 94, intellect: 92, politics: 85, age: 33, personality: 'proud', affinities: { sunquan: 95 }, loyalty: 95, isMonarch: false, stationedSiteId: 'chaisang', troops: 8000, tier: null },
  { id: 'lusu', name: '鲁肃', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 55, command: 76, intellect: 93, politics: 88, age: 36, personality: 'open', affinities: { sunquan: 88, liubei: 65 }, loyalty: 92, isMonarch: false, stationedSiteId: 'jianye', troops: 3000, tier: null },
  { id: 'zhangzhao', name: '张昭', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 30, command: 50, intellect: 90, politics: 92, age: 52, personality: 'cautious', affinities: { sunquan: 90 }, loyalty: 88, isMonarch: false, stationedSiteId: 'jianye', troops: 1000, tier: null },
  { id: 'zhanghong', name: '张纮', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 28, command: 48, intellect: 88, politics: 88, age: 56, personality: 'steady', affinities: { sunquan: 88 }, loyalty: 87, isMonarch: false, stationedSiteId: 'wu', troops: 1000, tier: null },
  { id: 'chengpu', name: '程普', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 84, command: 86, intellect: 70, politics: 65, age: 58, personality: 'brave', affinities: { sunquan: 94 }, loyalty: 94, isMonarch: false, stationedSiteId: 'wu', troops: 5000, tier: null },
  { id: 'huanggai', name: '黄盖', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 83, command: 82, intellect: 66, politics: 55, age: 63, personality: 'brave', affinities: { sunquan: 93 }, loyalty: 93, isMonarch: false, stationedSiteId: 'wu', troops: 5000, tier: null },
  { id: 'handang', name: '韩当', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 85, command: 80, intellect: 58, politics: 50, age: 56, personality: 'brave', affinities: { sunquan: 92 }, loyalty: 92, isMonarch: false, stationedSiteId: 'kuaiji', troops: 4000, tier: null },
  { id: 'taishici', name: '太史慈', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 90, command: 84, intellect: 70, politics: 60, age: 42, personality: 'brave', affinities: { sunquan: 70 }, loyalty: 88, isMonarch: false, stationedSiteId: 'yuzhang', troops: 4000, tier: null },
  { id: 'ganning', name: '甘宁', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 92, command: 82, intellect: 72, politics: 40, age: 33, personality: 'brave', affinities: { sunquan: 68 }, loyalty: 80, isMonarch: false, stationedSiteId: 'danyang', troops: 4000, tier: null },
  { id: 'lumeng', name: '吕蒙', status: 'serving', factionId: 'sunquan', provinceId: 'yang', might: 81, command: 89, intellect: 84, politics: 78, age: 30, personality: 'scheming', affinities: { sunquan: 88 }, loyalty: 90, isMonarch: false, stationedSiteId: 'poyang', troops: 5000, tier: null },

  // 在野（荆州）——荆襄名士置于基础池
  { id: 'huangzhong', name: '黄忠', status: 'wild', factionId: null, provinceId: 'jing', might: 93, command: 88, intellect: 62, politics: 45, age: 60, personality: 'brave', affinities: { liubei: 85 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'weiyan', name: '魏延', status: 'wild', factionId: null, provinceId: 'jing', might: 90, command: 86, intellect: 72, politics: 40, age: 34, personality: 'proud', affinities: { liubei: 80 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'pangtong', name: '庞统', status: 'wild', factionId: null, provinceId: 'jing', might: 36, command: 80, intellect: 97, politics: 90, age: 29, personality: 'proud', affinities: { liubei: 82 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'maliang', name: '马良', status: 'wild', factionId: null, provinceId: 'jing', might: 30, command: 60, intellect: 88, politics: 88, age: 21, personality: 'steady', affinities: { liubei: 85 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'masu', name: '马谡', status: 'wild', factionId: null, provinceId: 'jing', might: 60, command: 68, intellect: 82, politics: 76, age: 18, personality: 'proud', affinities: { liubei: 88 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'yiji', name: '伊籍', status: 'wild', factionId: null, provinceId: 'jing', might: 40, command: 55, intellect: 80, politics: 78, age: 28, personality: 'open', affinities: { liubei: 80 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'huojun', name: '霍峻', status: 'wild', factionId: null, provinceId: 'jing', might: 80, command: 82, intellect: 66, politics: 60, age: 30, personality: 'steady', affinities: { liubei: 82 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'xianglang', name: '向朗', status: 'wild', factionId: null, provinceId: 'jing', might: 45, command: 60, intellect: 78, politics: 80, age: 41, personality: 'steady', affinities: { liubei: 80 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'liaohua', name: '廖化', status: 'wild', factionId: null, provinceId: 'jing', might: 78, command: 75, intellect: 66, politics: 55, age: 18, personality: 'steady', affinities: { liubei: 85 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  { id: 'liuba', name: '刘巴', status: 'wild', factionId: null, provinceId: 'jing', might: 25, command: 55, intellect: 86, politics: 90, age: 24, personality: 'cautious', affinities: { liubei: 62 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  // 在野（司隶）
  { id: 'simayi', name: '司马懿', status: 'wild', factionId: null, provinceId: 'sili', might: 63, command: 90, intellect: 98, politics: 92, age: 29, personality: 'scheming', affinities: { caocao: 75 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'third' },
  // 在野（凉州）
  { id: 'machao', name: '马超', status: 'wild', factionId: null, provinceId: 'liang', might: 97, command: 90, intellect: 55, politics: 40, age: 32, personality: 'brave', affinities: {}, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'third' },
  { id: 'pangde', name: '庞德', status: 'wild', factionId: null, provinceId: 'liang', might: 94, command: 85, intellect: 62, politics: 45, age: 38, personality: 'steady', affinities: { caocao: 78 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'madai', name: '马岱', status: 'wild', factionId: null, provinceId: 'liang', might: 82, command: 78, intellect: 62, politics: 45, age: 25, personality: 'steady', affinities: {}, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'zhanglu', name: '张鲁', status: 'wild', factionId: null, provinceId: 'liang', might: 60, command: 70, intellect: 72, politics: 70, age: 38, personality: 'cautious', affinities: {}, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'yanpu', name: '阎圃', status: 'wild', factionId: null, provinceId: 'liang', might: 35, command: 58, intellect: 80, politics: 78, age: 40, personality: 'cautious', affinities: {}, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'basic' },
  // 在野（益州）
  { id: 'fazheng', name: '法正', status: 'wild', factionId: null, provinceId: 'yi', might: 40, command: 70, intellect: 93, politics: 85, age: 32, personality: 'scheming', affinities: { liubei: 85 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'third' },
  { id: 'zhangsong', name: '张松', status: 'wild', factionId: null, provinceId: 'yi', might: 20, command: 40, intellect: 84, politics: 78, age: 38, personality: 'open', affinities: { liubei: 82 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'huangquan', name: '黄权', status: 'wild', factionId: null, provinceId: 'yi', might: 55, command: 72, intellect: 85, politics: 82, age: 22, personality: 'steady', affinities: { liubei: 65 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'liyan', name: '李严', status: 'wild', factionId: null, provinceId: 'yi', might: 72, command: 78, intellect: 80, politics: 80, age: 30, personality: 'scheming', affinities: { liubei: 62 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'yanyan', name: '严颜', status: 'wild', factionId: null, provinceId: 'yi', might: 85, command: 82, intellect: 66, politics: 50, age: 58, personality: 'brave', affinities: { liubei: 68 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  // 在野（幽州、并州、交州）
  { id: 'tianchou', name: '田畴', status: 'wild', factionId: null, provinceId: 'you', might: 50, command: 65, intellect: 82, politics: 80, age: 39, personality: 'steady', affinities: { caocao: 68 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'zhangyan', name: '张燕', status: 'wild', factionId: null, provinceId: 'bing', might: 80, command: 78, intellect: 62, politics: 55, age: 48, personality: 'brave', affinities: { caocao: 65 }, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
  { id: 'shixie', name: '士燮', status: 'wild', factionId: null, provinceId: 'jiao', might: 50, command: 68, intellect: 76, politics: 80, age: 71, personality: 'cautious', affinities: {}, loyalty: 0, isMonarch: false, stationedSiteId: null, troops: 0, tier: 'second' },
]
